spring:
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017
  mongodb:
    embedded:
      version: "5.0.5"
      storage:
        repl-set-name: rs0
        oplogSize: 10

logging:
  level:
    ROOT: INFO
    com.dsgaur.spring.embedded.demo: DEBUG