spring:
  data:
    mongodb:
      database: product_db
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: rootpassword
  kafka:
    bootstrapAddress: localhost:9092

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.azunitech.cleancode: DEBUG

app:
  topic:
    success: success
